config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos do
    member do
      post :complete
    end
  end
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :title, :due_date

  def overdue
    return DateTime.now > self.due_date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :fetch_todo, :only => [:show, :edit, :update, :destroy, :complete]
	def index
		@todos = Todo.all
	end

  def update
    if @todo.update_attributes(todo_params)
      redirect_to todo_path(@todo)
    else
      render :action => "edit"
    end
  end

  def complete
    done = !@todo.done
    @todo.update_attributes(:done => done)
    redirect_to todos_path
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_path
    else
      render :action => "new"
    end
  end

  def destroy
    @todo.destroy

    redirect_to todos_path
  end

  private
  def fetch_todo
    @todo = Todo.find(params[:id])
  end

  private
  def todo_params
    params.require(:todo).permit(:title, :due_date, :note, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LhAssignmentS10</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<% if @todo.errors.present? %>
  <div class="container" role="alert">
    <ul class="list-group">
      <% @todo.errors.each do |error, message| %>
        <li class="list-group-item list-group-item-danger"> <%= "#{error.capitalize}  #{message}" %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form container">
  <%= form_for @todo do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :due_date %>
      <div class="form-control"><%= date_select :todo, :due_date %></div>
    </div>
    <div class="form-group">
      <%= f.label :note %>
      <%= f.text_area :note, class: "form-control" %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/todos/edit.html.erb
<%= render :partial => "form" %>

app/views/todos/index.html.erb
<div class="container">
  <table class="table table-striped table-condensed table-hover">
    <th>
      <tr>
        <td> </td>
        <td>Title</td>
        <td>Due Date</td>
        <td>Action</td>
      </tr>
    </th>
    <tbody>
    <% @todos.each do |todo| %>
     <tr>
      <td>
        <% if todo.done %>
          <%= link_to complete_todo_path(todo), method: :complete do %>
            <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
          <% end %>
        <% else %>
          <%= link_to complete_todo_path(todo), method: :complete do %>
            <span class="glyphicon glyphicon-unchecked" aria-hidden="true"></span>
          <% end %>
        <% end %>
      </td>
      <td><%= todo.title %></td>
      <td><%= todo.due_date %></td>
      <td>
        <%= link_to 'Show', todo_path(todo) %>
        <%= link_to 'Edit', edit_todo_path(todo) %>
        <% if !todo.overdue %>
          <%= link_to 'Destroy', todo_path(todo), method: :delete, data:{ confirm: "Are you sure?" } %>
        <% end %>
      </td>
     </tr>
    <% end %>
  </tbody>
  </table>
  <%= link_to 'New Todo', new_todo_path, class: "btn btn-default" %>
</div>

app/views/todos/new.html.erb
<%= render :partial => "form" %>

app/views/todos/show.html.erb
<div class="container">
  <table class="table table-bordered">
    <tr>
      <th>Title</th>
      <td><%= @todo.title %></td>
    </tr>
    <tr>
      <th>Due Date</th>
      <td><%= @todo.due_date %></td>
    </tr>
    <tr>
      <th>Note</th>
      <td><%= @todo.note %></td>
    </tr>
  </table>

  <%= link_to 'Back to index', todos_path %>
</div>